EventSync/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("main.urls")),
    path("portal/", include("portal.urls")),
    path("event/", include("event.urls")),
    path("chat/", include("chat.urls")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views  # Import all views from the current module
from django.shortcuts import render

app_name = "cart"


urlpatterns = [
    path("add/<int:event_id>/", views.add_to_cart, name="add_to_cart"),
    path("", views.view_cart, name="view_cart"),
    path("delete/<int:cart_item_id>/", views.delete_from_cart, name="delete_from_cart"),
    path("checkout/", views.checkout, name="checkout"),  # Checkout page
    path(
        "create-payment-intent/",
        views.create_payment_intent,
        name="create_payment_intent",
    ),  # Payment Intent API
    path("thank-you/", views.thank_you, name="thank_you"),
]

chat/urls.py
from django.urls import path
from .views import InboxView, ChatDetailView, NewChatView

app_name = "chat"

urlpatterns = [
    path("", InboxView.as_view(), name="inbox"),
    path("<int:pk>/", ChatDetailView.as_view(), name="detail"),
    path("new/<int:item_pk>/", NewChatView.as_view(), name="new_chat"),
]

event/urls.py
from django.urls import path
from cart.views import add_to_cart
from .views import (
    EventDetailView,
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
)

app_name = "event"

urlpatterns = [
    path("events/", EventListView.as_view(), name="browse_events"),
    path("new/", EventCreateView.as_view(), name="create_event"),
    path("<int:pk>/", EventDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", EventUpdateView.as_view(), name="edit_event"),
    path("<int:pk>/delete/", EventDeleteView.as_view(), name="delete_event"),
    path("<int:event_id>/add-to-cart/", add_to_cart, name="add_to_cart"),
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth

from .views import HomeView, RegistrationView
from .forms import AccessForm

app_name = "main"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("logout/", auth.LogoutView.as_view(), name="logout"),
    path(
        "login/",
        auth.LoginView.as_view(
            template_name="main/login.html",
            authentication_form=AccessForm,
        ),
        name="login",
    ),
]

portal/urls.py
from django.urls import path
from .views import PortalIndexView

app_name = "portal"

urlpatterns = [
    path("", PortalIndexView.as_view(), name="index"),
]

main/models.py
from django.db import models

# Create your models here.
import psycopg2

DB_CONFIG = {
    "dbname": "eventsync",
    "user": "postgres",
    "password": "postgres",
    "host": "localhost",
    "port": "5432",
}

def get_db_connection():
    """Establish and return a connection to the database."""
    return psycopg2.connect(**DB_CONFIG)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


# Define as a class inheriting UserCreationForm
class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email address",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )


# Rename this to LoginForm if you prefer consistency
class AccessForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

main/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, FormView
from django.urls import reverse_lazy

from event.models import Category, Event
from .forms import RegistrationForm


class HomeView(ListView):
    model = Event
    template_name = "main/index.html"
    context_object_name = "events"

    def get_queryset(self):
        # Only fetch the first 6 unsold events
        return Event.objects.filter(is_sold=False)[:6]

    def get_context_data(self, **kwargs):
        # Add categories to the context
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class RegistrationView(FormView):
    template_name = "main/registration.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("main:login")  # Redirect to login after registration

    def form_valid(self, form):
        # Save the form and redirect
        form.save()
        return super().form_valid(form)

main/templates/main/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}| EventSync {% endblock title %}</title>
</head>

<body class="bg-sky-50 text-sky-800 min-h-screen flex flex-col">
    <!-- Navigation -->
    <nav class="py-6 px-7 flex justify-between items-center bg-sky-600 shadow-xl">
        <a href="/" class="text-2xl font-bold text-sky-50">EventSync</a>
        <div class="flex items-center">
            {% if request.user.is_authenticated %}
            <!-- Show these links for authenticated users -->
            <a href="{% url 'event:create_event' %}" class="text-white hover:text-sky-300 font-bold mx-4">Create Event</a>
            <a href="{% url 'event:browse_events' %}" class="text-white hover:text-sky-300 font-bold mx-4">Browse Events</a>
            <a href="{% url 'portal:index' %}" class="text-white hover:text-sky-300 font-bold mx-4">Portal</a>
            <a href="{% url 'chat:inbox' %}" class="text-white hover:text-sky-300 font-bold mx-4">Inbox</a>

            <!-- Cart Button -->
            <a href="{% url 'cart:view_cart' %}" class="bg-green-500 text-white px-8 py-3 font-bold rounded-lg mx-4 hover:bg-green-600">
                Cart (<span id="cart-item-count">{{ cart_item_count }}</span>)
            </a>

            <a href="{% url 'main:logout' %}" class="bg-white text-sky-600 px-8 py-3 font-bold hover:bg-sky-100 rounded-lg">Logout</a>
            {% else %}
            <!-- Show these links for unauthenticated users -->
            <a href="{% url 'event:browse_events' %}" class="text-white hover:text-sky-300 font-bold mx-4">Browse Events</a>
            <a href="{% url 'main:login' %}" class="bg-white text-sky-600 px-8 py-3 font-bold hover:bg-sky-100 rounded-lg">Login</a>
            {% endif %}
        </div>
    </nav>

    <!-- Main Content -->
    <div class="flex-grow">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Footer -->
    <footer class="py-7 px-7 bg-sky-900 text-sky-50 text-center">
        <p>&copy; 2024 EventSync | Find and Create Events Around You</p>
    </footer>
</body>

</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Welcome {% endblock title %}

{% block content %}
<!-- Hero Section -->
<section class="relative text-center bg-sky-600 text-white h-[calc(70vh-100px)]">
    <img src="{% static 'images/party.jpg' %}" alt="Party Event" class="absolute top-0 left-0 w-full h-full object-cover object-center opacity-50 z-0">
    <div class="relative z-10 flex flex-col items-center justify-center h-full">
        <h1 class="text-5xl font-bold mb-4">Discover & Create Events With Ease</h1>
        {% if user.is_authenticated %}
        <p class="text-lg mb-6">Welcome back, {{ user.username }}! Ready to discover or manage events?</p>
        <div class="flex space-x-4">
            <a href="{% url 'event:browse_events' %}" class=" bg-white font-bold text-sky-600 px-8 py-3 rounded-md shadow-md hover:bg-sky-100">Browse Events</a>
        </div>
        {% else %}
        <p class="text-lg mb-6">Find local events, connect with people, or host your own in just a few clicks.</p>
        <div class="flex space-x-4">
            <a href="{% url 'main:registration' %}" class=" bg-white font-bold text-sky-600 px-8 py-3 rounded-md shadow-md hover:bg-sky-100">Join Now</a>
        </div>
        {% endif %}
    </div>
</section>

<!-- About Section -->
<section class="py-16 px-16">
    <div class="container mx-auto text-center">
        <h2 class="text-3xl font-bold mb-6">What is EventSync?</h2>
        <p class="text-lg mb-4 text-sky-600">EventSync is your one-stop platform for discovering exciting events around you and hosting your own. Whether you're looking to attend a concert, a workshop, or a networking event, we make it easy to find and join events that match your interests.</p>
        <p class="text-lg text-sky-600">Want to host? We've got you covered! Create and promote your event with just a few clicks, and watch the crowd grow.</p>
    </div>
</section>

<!-- Features Section -->
<section class="py-16 px-16 bg-sky-100">
    <div class="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
        <!-- Feature 1 -->
        <div class="p-8 bg-white shadow-md rounded-lg">
            <h3 class="text-2xl font-bold mb-4">Find Local Events</h3>
            <p class="text-sky-600">Search through a wide range of events in your area and never miss out on the fun.</p>
        </div>
        <!-- Feature 2 -->
        <div class="p-8 bg-white shadow-md rounded-lg">
            <h3 class="text-2xl font-bold mb-4">Host Your Own</h3>
            <p class="text-sky-600">Easily create and promote your event to attract attendees with a few clicks.</p>
        </div>
        <!-- Feature 3 -->
        <div class="p-8 bg-white shadow-md rounded-lg">
            <h3 class="text-2xl font-bold mb-4">Connect with People</h3>
            <p class="text-sky-600">Join a community of event-goers and connect with people who share your interests.</p>
        </div>
    </div>
</section>
{% endblock content %}

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="flex justify-center items-start pt-16">
    <div class="w-full max-w-md p-6 bg-white shadow-lg rounded-xl">
        <h1 class="text-3xl font-semibold text-center mb-6">Log in</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="space-y-4">
                <div>
                    {{ form.username.label_tag }}
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>

                <div>
                    {{ form.password.label_tag }}
                    {{ form.password }}
                    {{ form.password.errors }}
                </div>
            </div>

            {% if form.errors %}
            <div class="my-4 p-4 bg-red-100 text-red-600 rounded-xl">
                {% for field, errors in form.errors.items %}
                {% for error in errors %}
                <p>{{ error }}</p>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}

            <button class="mt-6 w-full py-3 bg-teal-500 text-white font-semibold rounded-xl hover:bg-teal-700">
                Submit
            </button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/registration.html
{% extends "main/base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="flex justify-center items-center min-h-screen">
    <div class="w-full max-w-md p-6 bg-white shadow-lg rounded-xl">
        <h1 class="text-3xl font-semibold text-center mb-6">Sign up</h1>

        <form method="post" action="{% url 'main:registration' %}">
            {% csrf_token %}

            <div class="space-y-4">
                <div>
                    {{ form.username.label_tag }}
                    {{ form.username }}
                </div>

                <div>
                    {{ form.email.label_tag }}
                    {{ form.email }}
                </div>

                <div>
                    {{ form.password1.label_tag }}
                    {{ form.password1 }}
                </div>

                <div>
                    {{ form.password2.label_tag }}
                    {{ form.password2 }}
                </div>
            </div>

            {% if form.errors %}
            <div class="my-4 p-4 bg-red-100 text-red-600 rounded-xl">
                {% for field, errors in form.errors.items %}
                {% for error in errors %}
                <p>{{ error }}</p>
                {% endfor %}
                {% endfor %}
            </div>
            {% endif %}

            <button class="mt-6 w-full py-3 bg-teal-500 text-white font-semibold rounded-xl hover:bg-teal-700">
                Submit
            </button>
        </form>
    </div>
</div>
{% endblock %}